/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import static GUI.Escritorio.PanelPrincipaljsjs;

/**
 *
 * @author matia
 */
public class Menu_Administrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Administrador
     */
    
    
    
    public Menu_Administrador() {
                super("Administrador", true, true, true, true);
        setSize(800, 500);
        setLocation(50, 50);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GestionUsuarioBT = new javax.swing.JButton();
        ReportesBT = new javax.swing.JButton();
        CerrarSesionBT = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Panel de Administración");

        GestionUsuarioBT.setText("Gestión de Usuarios");
        GestionUsuarioBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsuarioBTActionPerformed(evt);
            }
        });

        ReportesBT.setText("Reportes");
        ReportesBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesBTActionPerformed(evt);
            }
        });

        CerrarSesionBT.setText("Cerrar Sesión");
        CerrarSesionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GestionUsuarioBT)
                    .addComponent(jLabel1)
                    .addComponent(ReportesBT, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(CerrarSesionBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(GestionUsuarioBT)
                .addGap(12, 12, 12)
                .addComponent(ReportesBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrarSesionBT)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportesBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesBTActionPerformed
        
            Reportes Popelle = new Reportes();          
            PanelPrincipaljsjs.add(Popelle);      
            Popelle.setVisible(true);
        
    }//GEN-LAST:event_ReportesBTActionPerformed

    private void GestionUsuarioBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsuarioBTActionPerformed
        
            Gestion_Usuarios Popelle = new Gestion_Usuarios();          
            PanelPrincipaljsjs.add(Popelle);      
            Popelle.setVisible(true);
        
    }//GEN-LAST:event_GestionUsuarioBTActionPerformed

    private void CerrarSesionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionBTActionPerformed
        
    this.dispose(); 
    
    for (java.awt.Component comp : PanelPrincipaljsjs.getComponents()) {
        if (comp instanceof Menu_Administrador) {
            comp.setVisible(true); 
            try {
                ((javax.swing.JInternalFrame) comp).setSelected(true);
            } catch (Exception e) { }
            return;
        }
    }
    
    
    Login menu = new Login();
    PanelPrincipaljsjs.add(menu);
    menu.setVisible(true);
        
    }//GEN-LAST:event_CerrarSesionBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesionBT;
    private javax.swing.JButton GestionUsuarioBT;
    private javax.swing.JButton ReportesBT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
